### ISSUE TITLE
RE: The Book/Seth

### ISSUE THREAD

**Issue by silver2row** [ALIBERA/linux_book_2nd_edition#1]
Hello Sir,

Seth here. I just picked up an electronic copy of your book from Amazon.com. 

…

I noticed the boards that were used in the process of making this book. I also noticed that the DigiKey.com eeWiki has some info on the Xplained Ultra. I would like to learn more and I am happy that I have your book. Although this is a minor infraction, I would like to ask a couple of questions.

- Does the PICO, from this page https://shop.technexion.com/pico-pi-imx7.html, have the capability to be exchanged for the MCIMX7SABRE in your book?

and...

- If so, would you think I could use your GitHub.com page for inquiring about the book and the processes regarding embedding Linux in the exchanged machine?

Seth

P.S. The Xplained Ultra is no longer produced and the MCIMX7SABRE is very expensive to me. Please reply if you have any time on your hands.

**Comment by ALIBERA** [comment]
Hi Seth, any board based on i.MX7 or SAMA5D2 could be ok to develop the labs, it should only have a SPI controller and I2C controller and some GPIOs available. I think that most of the boards match these features. You only need to do some effort to add the Device tree info of the drivers under the DT SPI/I2C controller nodes that are available for your board, and the same for the GPIOs. I already ported all the drivers to the new SAMA5D2 board based on the SAMA5D27-SOM1-EK1 . Best Regards

**Comment by silver2row** [comment]
Hello,

Thank you. I will keep learning from your book.

Seth
